{
 "title": "Consul [bitte]",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Leadership", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raft Elections Changes",
   "type": "graph",
   "description": "Shows how many raft election changes have occurred in a 1 hour period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes((union(consul_raft_state_candidate_value,0))[1h]))",
     "legendFormat": "Raft elections changes over 1 hr"
    }
   ]
  },
  {
   "title": "Raft Leader Changes",
   "type": "graph",
   "description": "This panel shows raft leader changes per hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes(union(consul_raft_state_leader_value, 0)[1h]))",
     "legendFormat": "Raft leader changes over 1 hr"
    }
   ]
  },
  {
   "title": "Raft Leader Last Contact",
   "type": "graph",
   "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Core Node Memory Utilization",
   "type": "graph",
   "description": "If memory use becomes too high on core nodes, OOM killer may start consul or vault service flapping",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"core.*\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Transaction Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Raft Commit Time",
   "type": "graph",
   "description": "This measures the time it takes to commit a new entry to the Raft log on the leader.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_commitTime_count", "legendFormat": "{{host}}" },
    {
     "expr": "avg_over_time(consul_raft_commitTime_count[1h])",
     "legendFormat": "{{host}}-(1 hr avg)"
    }
   ]
  },
  {
   "title": "Raft Apply",
   "type": "graph",
   "description": "This counts the number of Raft transactions occurring over the interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_raft_apply_value", "legendFormat": "{{host}}" },
    {
     "expr": "avg_over_time(consul_raft_apply_value[1h])",
     "legendFormat": "{{host}}-(1 hr avg)"
    }
   ]
  },
  {
   "title": "KVs apply",
   "type": "graph",
   "description": "This measures the time it takes to complete an update to the KV store.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_kvs_apply_count", "legendFormat": "{{host}}" }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "DNS Queries",
   "type": "graph",
   "description": "Shows the average number of domain queries per node over a 1 hour period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "avg queries/hr" } },
   "yaxes": [
    { "format": "avg queries/hr" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(union(consul_dns_domain_query_count,label_set(0,\"host\",\"baseline\"))[1h]) default 0",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "sum(avg_over_time(union(consul_dns_domain_query_count{host=~\"core.*\"},label_set(0,\"host\",\"baseline\"))[1h])) default 0",
     "legendFormat": "core-node-sum"
    }
   ]
  },
  { "title": "ACL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "ACL Resolves",
   "type": "graph",
   "description": "Counts the average ACL tokens count resolved over a 5 minute period. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "avg ops/5m" } },
   "yaxes": [
    { "format": "avg ops/5m" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(consul_acl_ResolveToken_count[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Catalog Operations",
   "type": "graph",
   "description": "This shows the average catalog register and deregister operations in a 1 hour period. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "avg ops/1h" } },
   "yaxes": [
    { "format": "avg ops/1h" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(union(consul_catalog_register_count,label_set(0,\"host\",\"baseline\"))[1h]) default 0",
     "legendFormat": "{{host}}-register"
    },
    {
     "expr": "avg_over_time(union(consul_catalog_deregister_count,label_set(0,\"host\",\"baseline\"))[1h]) default 0",
     "legendFormat": "{{host}}-deregister"
    }
   ]
  }
 ]
}